 # Form implementation generated from reading ui file '.\test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon
import subprocess


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setWindowTitle("Menü")
        Dialog.setWindowIcon(QIcon("./hat_98438.ico"))
        Dialog.setObjectName("Menu")
        Dialog.resize(275, 219)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 70, 101, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked(subprocess.call([r'./Texterkennung.py']))
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 100, 101, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 160, 101, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 130, 101, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(110, 50, 91, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Herunterfahren"))
        self.pushButton_2.setText(_translate("Dialog", "OneNote"))
        self.pushButton_3.setText(_translate("Dialog", "Brave"))
        self.pushButton_4.setText(_translate("Dialog", "NilsGame"))
        self.label.setText(_translate("Dialog", "Optionen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
